-- ==========================================
-- 1. Create DEPARTMENTS Table & RLS Policies
-- ==========================================
CREATE TABLE "DEPARTMENTS" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(100) NOT NULL
);

ALTER TABLE "DEPARTMENTS" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow select for all users DEPT" ON "DEPARTMENTS" FOR SELECT USING (true);
CREATE POLICY "Allow insert for all users DEPT" ON "DEPARTMENTS" FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow update for all users DEPT" ON "DEPARTMENTS" FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Allow delete for all users DEPT" ON "DEPARTMENTS" FOR DELETE USING (true);

-- ==========================================
-- 2. Create EMPLOYEE_STATUSES Table & RLS Policies
-- ==========================================
CREATE TABLE "EMPLOYEE_STATUSES" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "name" VARCHAR(100) NOT NULL
);

ALTER TABLE "EMPLOYEE_STATUSES" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow select for all users STATUS" ON "EMPLOYEE_STATUSES" FOR SELECT USING (true);
CREATE POLICY "Allow insert for all users STATUS" ON "EMPLOYEE_STATUSES" FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow update for all users STATUS" ON "EMPLOYEE_STATUSES" FOR UPDATE USING (true) WITH CHECK (true);
CREATE POLICY "Allow delete for all users STATUS" ON "EMPLOYEE_STATUSES" FOR DELETE USING (true);

-- Refresh the Supabase Cache
NOTIFY pgrst, 'reload schema';
