-- PostgreSQL (Supabase) version
-- This matches your Supabase usage in the project.
CREATE TABLE "RELIGION" (
    "RNo" BIGINT NOT NULL,
    "ReligionList" VARCHAR(30) NOT NULL,
    PRIMARY KEY ("RNo")
);

-- If you want the RNo to auto-increment, uncomment the following line and delete the RNo line above:
-- "RNo" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

-- Refresh Supabase cache so the API recognizes the new table
NOTIFY pgrst, 'reload schema';


-- ==============================================
-- SQL Server version (Exact matches your screenshot)
-- ==============================================
-- CREATE TABLE [dbo].[RELIGION] (
--     [RNo] BIGINT NOT NULL,
--     [ReligionList] NVARCHAR(30) NOT NULL,
--     CONSTRAINT [PK_RELIGION] PRIMARY KEY CLUSTERED ([RNo])
-- );
