-- ============================================================
--  EMPDETAILS Table Schema for AJG Security
--  Run this in your Supabase SQL Editor
--  This creates (or recreates) the EMPDETAILS table with
--  every column used by EmployeeRegistration.tsx.
--  NULL-safe: all non-required columns default to NULL or ''.
-- ============================================================

-- Drop the table first if you want a clean slate (optional).
-- WARNING: This will delete all existing employee data!
-- DROP TABLE IF EXISTS "EMPDETAILS";

-- Create the table
CREATE TABLE IF NOT EXISTS "EMPDETAILS" (
  -- ── Primary Key ──────────────────────────────────────────
  "EmplID"        BIGINT        PRIMARY KEY,          -- numeric employee ID (generated by the app)

  -- ── Identification ───────────────────────────────────────
  "idno"          TEXT          NOT NULL DEFAULT '',  -- e.g. EMP-123456
  "Fname"         TEXT          NOT NULL DEFAULT '',
  "MName"         TEXT                   DEFAULT '',
  "LName"         TEXT          NOT NULL DEFAULT '',

  -- ── Personal Info ────────────────────────────────────────
  "Bdate"         TEXT                   DEFAULT '',  -- stored as text date string
  "Age"           INTEGER                DEFAULT 0,
  "BloodType"     TEXT                   DEFAULT '',
  "CivilStatus"   TEXT                   DEFAULT '',
  "Gender"        TEXT                   DEFAULT '',
  "Religion"      TEXT                   DEFAULT '',
  "heightCm"      NUMERIC(6,2)           DEFAULT 0,
  "weightLb"      NUMERIC(6,2)           DEFAULT 0,

  -- ── Contact & Address ────────────────────────────────────
  "ContactNo"     TEXT                   DEFAULT '',
  "EmailAdd"      TEXT                   DEFAULT '',
  "CAddress"      TEXT                   DEFAULT '',  -- Current Address
  "PAddress"      TEXT                   DEFAULT '',  -- Permanent Address

  -- ── Family Background ────────────────────────────────────
  "FatherName"    TEXT                   DEFAULT '',
  "FOccupation"   TEXT                   DEFAULT '',
  "FContact"      TEXT                   DEFAULT '',
  "FAddress"      TEXT                   DEFAULT '',
  "MotherName"    TEXT                   DEFAULT '',
  "MOccupation"   TEXT                   DEFAULT '',
  "MContact"      TEXT                   DEFAULT '',
  "MAddress"      TEXT                   DEFAULT '',

  -- ── Emergency Contact ────────────────────────────────────
  "ECPerson"      TEXT                   DEFAULT '',
  "ECNo"          TEXT                   DEFAULT '',

  -- ── Compensation ─────────────────────────────────────────
  "EmpRate"       TEXT                   DEFAULT 'monthly',   -- 'monthly' | 'daily'
  "MonthlyRate"   NUMERIC(12,2)          DEFAULT 0,
  "DailyRate"     NUMERIC(12,2)          DEFAULT 0,
  "HourRate"      NUMERIC(12,2)          DEFAULT 0,
  "Allowance"     NUMERIC(12,2)          DEFAULT 0,

  -- ── Bank / Payroll ───────────────────────────────────────
  "CardNumber"    TEXT                   DEFAULT '',
  "BankAccount"   TEXT                   DEFAULT '',
  "BankType"      TEXT                   DEFAULT '',

  -- ── Employment ───────────────────────────────────────────
  "DTHired"       TEXT                   DEFAULT '',
  "EmpStatus"     TEXT                   DEFAULT '',
  "Position"      TEXT                   DEFAULT '',
  "Department"    TEXT                   DEFAULT '',
  "JobDescription" TEXT                  DEFAULT '',
  "QuitClaim"     TEXT                   DEFAULT 'no',

  -- ── Overtime Rates ───────────────────────────────────────
  "OTRegDay"      NUMERIC(6,4)           DEFAULT 0,
  "OTSunday"      NUMERIC(6,4)           DEFAULT 0,
  "OTSpecial"     NUMERIC(6,4)           DEFAULT 0,
  "OTLegal"       NUMERIC(6,4)           DEFAULT 0,
  "OTNightDiff"   NUMERIC(6,4)           DEFAULT 0,
  "OTNDBase"      NUMERIC(6,4)           DEFAULT 0,
  "OTNDAdd"       NUMERIC(6,4)           DEFAULT 0,

  -- ── Government Contributions (Monthly Amounts) ───────────
  "MempHDMF"      NUMERIC(12,2)          DEFAULT 0,   -- Employee share HDMF
  "MempSSS"       NUMERIC(12,2)          DEFAULT 0,   -- Employee share SSS
  "MempPHIC"      NUMERIC(12,2)          DEFAULT 0,   -- Employee share PHIC
  "MComHDMF"      NUMERIC(12,2)          DEFAULT 0,   -- Employer share HDMF
  "MComSSS"       NUMERIC(12,2)          DEFAULT 0,   -- Employer share SSS
  "MComPHIC"      NUMERIC(12,2)          DEFAULT 0,   -- Employer share PHIC

  -- ── Government ID Numbers ────────────────────────────────
  "HDMF"          TEXT                   DEFAULT '',
  "PHIC"          TEXT                   DEFAULT '',
  "SSS"           TEXT                   DEFAULT '',
  "TIN"           TEXT                   DEFAULT '',

  -- ── Education ────────────────────────────────────────────
  "LevelType"     TEXT                   DEFAULT '',   -- elementary / highschool / college / vocational
  "School"        TEXT                   DEFAULT '',
  "Course"        TEXT                   DEFAULT '',
  "EducAddress"   TEXT                   DEFAULT '',
  "DTYearGrad"    TEXT                   DEFAULT '',

  -- ── SG License ───────────────────────────────────────────
  "IDControlNo"   TEXT                   DEFAULT '',
  "Locator"       TEXT                   DEFAULT '',
  "IssueAt"       TEXT                   DEFAULT '',
  "OPNo"          TEXT                   DEFAULT '',
  "DTIssue"       TEXT                   DEFAULT '',
  "DTPaid"        TEXT                   DEFAULT '',
  "DTApproved"    TEXT                   DEFAULT '',
  "DTExpiry"      TEXT                   DEFAULT '',

  -- ── Timestamps ───────────────────────────────────────────
  "created_at"    TIMESTAMPTZ            DEFAULT NOW(),
  "updated_at"    TIMESTAMPTZ            DEFAULT NOW()
);

-- ── Trigger: auto-update updated_at on every row update ──────
CREATE OR REPLACE FUNCTION update_empdetails_timestamp()
RETURNS TRIGGER AS $$
BEGIN
  NEW."updated_at" = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_empdetails_updated_at ON "EMPDETAILS";
CREATE TRIGGER trg_empdetails_updated_at
  BEFORE UPDATE ON "EMPDETAILS"
  FOR EACH ROW EXECUTE FUNCTION update_empdetails_timestamp();

-- ── Row-Level Security (RLS) ─────────────────────────────────
-- Enable RLS so only authenticated users can read/write
ALTER TABLE "EMPDETAILS" ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if re-running
DROP POLICY IF EXISTS "Allow authenticated read"  ON "EMPDETAILS";
DROP POLICY IF EXISTS "Allow authenticated insert" ON "EMPDETAILS";
DROP POLICY IF EXISTS "Allow authenticated update" ON "EMPDETAILS";
DROP POLICY IF EXISTS "Allow authenticated delete" ON "EMPDETAILS";

-- Authenticated users can do everything (adjust to your needs)
CREATE POLICY "Allow authenticated read"
  ON "EMPDETAILS" FOR SELECT
  TO authenticated
  USING (true);

CREATE POLICY "Allow authenticated insert"
  ON "EMPDETAILS" FOR INSERT
  TO authenticated
  WITH CHECK (true);

CREATE POLICY "Allow authenticated update"
  ON "EMPDETAILS" FOR UPDATE
  TO authenticated
  USING (true)
  WITH CHECK (true);

CREATE POLICY "Allow authenticated delete"
  ON "EMPDETAILS" FOR DELETE
  TO authenticated
  USING (true);

-- ── Useful indexes ───────────────────────────────────────────
CREATE INDEX IF NOT EXISTS idx_empdetails_idno   ON "EMPDETAILS" ("idno");
CREATE INDEX IF NOT EXISTS idx_empdetails_lname  ON "EMPDETAILS" ("LName");

-- ── Done ──────────────────────────────────────────────────────
-- If the table already exists and you only want to ADD missing columns, 
-- use the ALTER TABLE statements below instead of the CREATE TABLE above:

/*
ALTER TABLE "EMPDETAILS"
  ADD COLUMN IF NOT EXISTS "OTNightDiff"   NUMERIC(6,4)  DEFAULT 0,
  ADD COLUMN IF NOT EXISTS "CardNumber"    TEXT          DEFAULT '',
  ADD COLUMN IF NOT EXISTS "DTYearGrad"    TEXT          DEFAULT '',
  ADD COLUMN IF NOT EXISTS "IDControlNo"   TEXT          DEFAULT '',
  ADD COLUMN IF NOT EXISTS "Locator"       TEXT          DEFAULT '',
  ADD COLUMN IF NOT EXISTS "IssueAt"       TEXT          DEFAULT '',
  ADD COLUMN IF NOT EXISTS "OPNo"          TEXT          DEFAULT '',
  ADD COLUMN IF NOT EXISTS "DTIssue"       TEXT          DEFAULT '',
  ADD COLUMN IF NOT EXISTS "DTPaid"        TEXT          DEFAULT '',
  ADD COLUMN IF NOT EXISTS "DTApproved"    TEXT          DEFAULT '',
  ADD COLUMN IF NOT EXISTS "DTExpiry"      TEXT          DEFAULT '',
  ADD COLUMN IF NOT EXISTS "created_at"    TIMESTAMPTZ   DEFAULT NOW(),
  ADD COLUMN IF NOT EXISTS "updated_at"    TIMESTAMPTZ   DEFAULT NOW();
*/
