-- Run this in your Supabase SQL Editor to make RNo auto-increment!
-- This will fix any the "null value in column RNo" error when adding a religion.

ALTER TABLE "RELIGION"
ALTER COLUMN "RNo" ADD GENERATED BY DEFAULT AS IDENTITY;

NOTIFY pgrst, 'reload schema';
