-- ==========================================
--  OVERTIMERATE Table for AJG Security
--  This table stores global overtime rate multipliers.
--  Only one row should exist (id=1).
-- ==========================================

-- If the table exists and you want a fresh start, uncomment the line below:
-- DROP TABLE IF EXISTS "OVERTIMERATE";

CREATE TABLE IF NOT EXISTS "OVERTIMERATE" (
    "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "RateOTRegDay" NUMERIC(6,4) DEFAULT 1.25,
    "RateOTSunday" NUMERIC(6,4) DEFAULT 1.30,
    "RateOTSpecial" NUMERIC(6,4) DEFAULT 1.30,
    "RateOTLegal" NUMERIC(6,4) DEFAULT 2.00,
    "RateOTNDBase" NUMERIC(6,4) DEFAULT 1.25,
    "RateOTNDAdd" NUMERIC(6,4) DEFAULT 0.10,
    "created_at" TIMESTAMPTZ DEFAULT NOW(),
    "updated_at" TIMESTAMPTZ DEFAULT NOW()
);

-- Enable RLS
ALTER TABLE "OVERTIMERATE" ENABLE ROW LEVEL SECURITY;

-- Drop existing policies if any
DROP POLICY IF EXISTS "Allow select for all OVERTIMERATE" ON "OVERTIMERATE";
DROP POLICY IF EXISTS "Allow insert for all OVERTIMERATE" ON "OVERTIMERATE";
DROP POLICY IF EXISTS "Allow update for all OVERTIMERATE" ON "OVERTIMERATE";

-- Create policies (Allows everyone to read and write for setup purposes)
CREATE POLICY "Allow select for all OVERTIMERATE" ON "OVERTIMERATE" FOR SELECT USING (true);
CREATE POLICY "Allow insert for all OVERTIMERATE" ON "OVERTIMERATE" FOR INSERT WITH CHECK (true);
CREATE POLICY "Allow update for all OVERTIMERATE" ON "OVERTIMERATE" FOR UPDATE USING (true) WITH CHECK (true);

-- Insert default row if table is empty
-- We use OVERRIDING SYSTEM VALUE to force id=1 even if Postgres is set to GENERATED ALWAYS
INSERT INTO "OVERTIMERATE" ("id", "RateOTRegDay", "RateOTSunday", "RateOTSpecial", "RateOTLegal", "RateOTNDBase", "RateOTNDAdd")
OVERRIDING SYSTEM VALUE
SELECT 1, 1.25, 1.30, 1.30, 2.00, 1.25, 0.10
WHERE NOT EXISTS (SELECT 1 FROM "OVERTIMERATE" WHERE id = 1);

-- Refresh the Supabase Cache
NOTIFY pgrst, 'reload schema';
