-- ENABLE RLS ON LOANS TABLE
ALTER TABLE "LOANS" ENABLE ROW LEVEL SECURITY;

-- CREATE POLICY TO ALLOW ANYONE TO READ (Standard for anon access)
DROP POLICY IF EXISTS "Allow anon select" ON "LOANS";
CREATE POLICY "Allow anon select" ON "LOANS" FOR SELECT USING (true);
