-- COMPREHENSIVE RLS FIX FOR MASTER DATA AND LOANS (FULL ACCESS)
-- Run this in Supabase SQL Editor to allow Adding/Editing/Deleting on Vercel

-- 1. LOANS
ALTER TABLE "LOANS" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon select" ON "LOANS";
DROP POLICY IF EXISTS "Allow anon all" ON "LOANS";
CREATE POLICY "Allow anon all" ON "LOANS" FOR ALL USING (true) WITH CHECK (true);

-- 2. LOAN_TYPES
ALTER TABLE "LOAN_TYPES" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon select" ON "LOAN_TYPES";
DROP POLICY IF EXISTS "Allow anon all" ON "LOAN_TYPES";
CREATE POLICY "Allow anon all" ON "LOAN_TYPES" FOR ALL USING (true) WITH CHECK (true);

-- 3. RELIGION
ALTER TABLE "RELIGION" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon select" ON "RELIGION";
DROP POLICY IF EXISTS "Allow anon all" ON "RELIGION";
CREATE POLICY "Allow anon all" ON "RELIGION" FOR ALL USING (true) WITH CHECK (true);

-- 4. EMPPOSITION
ALTER TABLE "EMPPOSITION" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon select" ON "EMPPOSITION";
DROP POLICY IF EXISTS "Allow anon all" ON "EMPPOSITION";
CREATE POLICY "Allow anon all" ON "EMPPOSITION" FOR ALL USING (true) WITH CHECK (true);

-- 5. DEPARTMENTS
ALTER TABLE "DEPARTMENTS" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon select" ON "DEPARTMENTS";
DROP POLICY IF EXISTS "Allow anon all" ON "DEPARTMENTS";
CREATE POLICY "Allow anon all" ON "DEPARTMENTS" FOR ALL USING (true) WITH CHECK (true);

-- 6. EMPLOYEE_STATUSES
ALTER TABLE "EMPLOYEE_STATUSES" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon select" ON "EMPLOYEE_STATUSES";
DROP POLICY IF EXISTS "Allow anon all" ON "EMPLOYEE_STATUSES";
CREATE POLICY "Allow anon all" ON "EMPLOYEE_STATUSES" FOR ALL USING (true) WITH CHECK (true);

-- 7. OVERTIMERATE
ALTER TABLE "OVERTIMERATE" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon select" ON "OVERTIMERATE";
DROP POLICY IF EXISTS "Allow anon all" ON "OVERTIMERATE";
CREATE POLICY "Allow anon all" ON "OVERTIMERATE" FOR ALL USING (true) WITH CHECK (true);

-- 8. EMPDETAILS
ALTER TABLE "EMPDETAILS" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon select" ON "EMPDETAILS";
DROP POLICY IF EXISTS "Allow anon all" ON "EMPDETAILS";
CREATE POLICY "Allow anon all" ON "EMPDETAILS" FOR ALL USING (true) WITH CHECK (true);
