-- COMPREHENSIVE RLS FIX FOR MASTER DATA AND LOANS
-- Run this in Supabase SQL Editor to fix empty sections on Vercel

-- 1. LOANS
ALTER TABLE "LOANS" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon select" ON "LOANS";
CREATE POLICY "Allow anon select" ON "LOANS" FOR SELECT USING (true);

-- 2. LOAN_TYPES
ALTER TABLE "LOAN_TYPES" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon select" ON "LOAN_TYPES";
CREATE POLICY "Allow anon select" ON "LOAN_TYPES" FOR SELECT USING (true);

-- 3. RELIGION
ALTER TABLE "RELIGION" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon select" ON "RELIGION";
CREATE POLICY "Allow anon select" ON "RELIGION" FOR SELECT USING (true);

-- 4. EMPPOSITION
ALTER TABLE "EMPPOSITION" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon select" ON "EMPPOSITION";
CREATE POLICY "Allow anon select" ON "EMPPOSITION" FOR SELECT USING (true);

-- 5. DEPARTMENTS
ALTER TABLE "DEPARTMENTS" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon select" ON "DEPARTMENTS";
CREATE POLICY "Allow anon select" ON "DEPARTMENTS" FOR SELECT USING (true);

-- 6. EMPLOYEE_STATUSES
ALTER TABLE "EMPLOYEE_STATUSES" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon select" ON "EMPLOYEE_STATUSES";
CREATE POLICY "Allow anon select" ON "EMPLOYEE_STATUSES" FOR SELECT USING (true);

-- 7. OVERTIMERATE
ALTER TABLE "OVERTIMERATE" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon select" ON "OVERTIMERATE";
CREATE POLICY "Allow anon select" ON "OVERTIMERATE" FOR SELECT USING (true);

-- 8. EMPDETAILS (Ensure employees are also visible)
ALTER TABLE "EMPDETAILS" ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Allow anon select" ON "EMPDETAILS";
CREATE POLICY "Allow anon select" ON "EMPDETAILS" FOR SELECT USING (true);
