-- UPGRADE RATE PRECISION TO 4 DECIMAL PLACES
ALTER TABLE "EMPDETAILS" ALTER COLUMN "DailyRate" TYPE DECIMAL(15, 4);
ALTER TABLE "EMPDETAILS" ALTER COLUMN "MonthlyRate" TYPE DECIMAL(15, 4);
ALTER TABLE "EMPDETAILS" ALTER COLUMN "HourRate" TYPE DECIMAL(15, 4);

ALTER TABLE "PAYROLLDATA" ALTER COLUMN "DailyRate" TYPE DECIMAL(15, 4);
ALTER TABLE "PAYROLLDATA" ALTER COLUMN "BasicRate" TYPE DECIMAL(15, 4);
ALTER TABLE "PAYROLLDATA" ALTER COLUMN "OTRegDay" TYPE DECIMAL(15, 4);
ALTER TABLE "PAYROLLDATA" ALTER COLUMN "OTSunday" TYPE DECIMAL(15, 4);
ALTER TABLE "PAYROLLDATA" ALTER COLUMN "OTSpecial" TYPE DECIMAL(15, 4);
ALTER TABLE "PAYROLLDATA" ALTER COLUMN "OTLegal" TYPE DECIMAL(15, 4);
ALTER TABLE "PAYROLLDATA" ALTER COLUMN "OTND" TYPE DECIMAL(15, 4);
